theme:

title: 'Terrapin Publications'

defaults:
  -
    scope:
      path: ""      # an empty string here means all files in the project
      type: pages
    values:
      # allow site search to reach this page, also enables the search field
      search: true
      # do not verify logins
      verify: false
      # display a TOC on page
      toc: true
      # sidebar settings
      sidebar: 
        file: _sidebar.md
        width: 250

exclude:
  - README.md
